[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-server]
command=php -S 0.0.0.0:8000 -t /var/www/html/public
directory=/var/www/html
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
environment=APP_ENV="production"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:horizon]
command=php artisan horizon
directory=/var/www/html
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
environment=APP_ENV="production"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
