[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:octane]
command=php artisan octane:start --server=%(ENV_OCTANE_SERVER)s --host=%(ENV_OCTANE_HOST)s --port=%(ENV_OCTANE_PORT)s --workers=%(ENV_OCTANE_WORKERS)s --task-workers=%(ENV_OCTANE_TASK_WORKERS)s --max-requests=%(ENV_OCTANE_MAX_REQUESTS)s --no-interaction
user=nobody
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopsignal=TERM
environment=LARAVEL_SAIL="1",APP_ENV="production"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue-worker]
command=php artisan queue:work redis --sleep=1 --tries=3 --timeout=120 --max-jobs=1000
user=nobody
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopsignal=TERM
environment=LARAVEL_SAIL="1",APP_ENV="production"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
