[program:pulse]
process_name=%(program_name)s
command=php /var/www/hackatonshik/artisan pulse:work
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/hackatonshik/storage/logs/pulse.log
stopwaitsecs=3600
